### ISSUE TITLE
Execute generated script in Cloud

### ISSUE THREAD

**Issue by supreme-gg-gg** [supreme-gg-gg/block-ml#2]
- Research how to use Google Colab API 
- Figure out the best automation workflow to send and execute the script
- Figure out how to access the output (if better visuals)

**Comment by AnnieL5** [comment]
Little information were found by Calo and I with two possibilities. One solution is to use Google Colab API with google drive(not figured out yet), the other is to write an automation program that pastes the code in Google Colab, press run, and copy the output somehow.
